'use client';
import { useEffect, useState } from 'react';import { useParams } from 'next/navigation';import { PageHeader } from '@/components/erp/shared';import Image from 'next/image';import { Button } from '@/components/ui/button';import toast from 'react-hot-toast';import { useErpData } from '@/components/erp/useErpData';

export default function UploadDetailPage() {
  const { id } = useParams<{ id: string }>(); const { data, refresh } = useErpData();
  const [upload, setUpload] = useState<any>(null); const [timeline,setTimeline]=useState<any[]>([]); const [matches, setMatches] = useState<any[]>([]); const [saving,setSaving]=useState(false);
  const load = async () => { const up = await fetch(`/api/uploads/${id}`).then(r=>r.json()); setUpload(up.data); const m = await fetch(`/api/uploads/${id}/matches`).then(r=>r.json()); setMatches(m.data||[]); const t = await fetch(`/api/v1/erp/activity?entityType=UPLOAD&entityId=${id}`).then(r=>r.json()); setTimeline(t.data||[]); };
  useEffect(() => { load(); }, [id]);
  const sales = data?.sales || []; const customers = data?.customers || []; const transactions = data?.transactions || [];
  const save = async () => { setSaving(true); const r = await fetch(`/api/uploads/${id}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(upload)}); setSaving(false); if(!r.ok)return toast.error('Erro ao salvar revisão'); toast.success('Revisão salva'); refresh(); load(); };
  const createTx = async () => { const r = await fetch('/api/v1/erp/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'INCOME',description:`OCR ${upload.banco||''}`,amount:Number(upload.valor||0),category:'OCR_PIX',status:'CONFIRMED'})}); const j=await r.json(); if(!r.ok)return toast.error('Falha'); setUpload({...upload,linkedTransactionId:j.data.id,reviewStatus:'REVIEWED'}); toast.success('Transação criada'); };
  const createSale = async () => { const first = data?.products?.find((p:any)=>p.active); if(!first)return toast.error('Cadastre ao menos 1 produto'); const r=await fetch('/api/v1/erp/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:upload.customerId||undefined,status:'PENDING',paymentMethod:'PIX',source:'OCR_PIX',items:[{productId:first.id,quantity:1,unitPrice:Number(upload.valor||first.price)}]})}); const j=await r.json(); if(!r.ok)return toast.error('Falha'); setUpload({...upload,linkedSaleId:j.data.id,reviewStatus:'REVIEWED'}); toast.success('Venda criada'); };
  const confirmMatch = async (saleId:string) => { if(!confirm('Confirmar reconciliação desta venda?')) return; const r=await fetch(`/api/uploads/${id}/confirm-match`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({saleId})}); if(!r.ok){const j=await r.json(); return toast.error(j.error?.message||'Falha');} toast.success('Pagamento reconciliado'); await load(); refresh(); };

  if (!upload) return <div>Carregando comprovante...</div>;
  return <div className='space-y-4'><PageHeader title={`Comprovante ${id.slice(0,8)}`} subtitle='Revisão OCR, vínculo ERP e reconciliação automática.'/>
    <div className='grid lg:grid-cols-2 gap-4'>
      <div className='bg-white border rounded p-4'>{upload.imageData ? <Image src={`data:image/png;base64,${upload.imageData}`} alt='Comprovante' width={700} height={900} className='w-full h-auto rounded'/> : 'Sem preview'}</div>
      <div className='bg-white border rounded p-4 text-sm space-y-2'>
        <div className='grid grid-cols-2 gap-2'><label>Banco<input className='border rounded h-9 px-2 w-full' value={upload.banco||''} onChange={e=>setUpload({...upload,banco:e.target.value})}/></label><label>Valor<input type='number' className='border rounded h-9 px-2 w-full' value={upload.valor||0} onChange={e=>setUpload({...upload,valor:e.target.value})}/></label></div>
        <label>Pagador<input className='border rounded h-9 px-2 w-full' value={upload.pagador||''} onChange={e=>setUpload({...upload,pagador:e.target.value})}/></label>
        <label>Recebedor<input className='border rounded h-9 px-2 w-full' value={upload.recebedor||''} onChange={e=>setUpload({...upload,recebedor:e.target.value})}/></label>
        <label>TXID<input className='border rounded h-9 px-2 w-full' value={upload.txId||''} onChange={e=>setUpload({...upload,txId:e.target.value})}/></label>
        <div className='grid grid-cols-2 gap-2'><label>Status revisão<select className='border rounded h-9 px-2 w-full' value={upload.reviewStatus||'PENDING'} onChange={e=>setUpload({...upload,reviewStatus:e.target.value})}><option>PENDING</option><option>REVIEWED</option><option>ARCHIVED</option></select></label><label>Cliente<select className='border rounded h-9 px-2 w-full' value={upload.customerId||''} onChange={e=>setUpload({...upload,customerId:e.target.value||null})}><option value=''>Sem vínculo</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
        <label>Venda<select className='border rounded h-9 px-2 w-full' value={upload.linkedSaleId||''} onChange={e=>setUpload({...upload,linkedSaleId:e.target.value||null})}><option value=''>Sem vínculo</option>{sales.map((s:any)=><option key={s.id} value={s.id}>{s.id.slice(0,8)} • {s.customer?.name||'-'}</option>)}</select></label>
        <label>Transação<select className='border rounded h-9 px-2 w-full' value={upload.linkedTransactionId||''} onChange={e=>setUpload({...upload,linkedTransactionId:e.target.value||null})}><option value=''>Sem vínculo</option>{transactions.map((t:any)=><option key={t.id} value={t.id}>{t.kind} • {t.description}</option>)}</select></label>
        <div className='flex flex-wrap gap-2 pt-2'><Button onClick={save} disabled={saving}>{saving?'Salvando...':'Salvar revisão'}</Button><Button variant='outline' onClick={createTx}>Criar transação</Button><Button variant='outline' onClick={createSale}>Criar venda</Button></div>
      </div>
    </div>
    <div className='bg-white border rounded p-4'><h3 className='font-medium mb-2'>Possíveis correspondências</h3>{matches.length?matches.map((m:any)=><div key={m.id} className='border rounded p-2 text-sm mb-2 flex items-center justify-between'><div>Venda #{m.sale.id.slice(0,8)} • {m.sale.customer?.name||'-'} • R$ {(m.sale.total-m.sale.discount+m.sale.freight).toFixed(2)} • confiança {m.confidenceScore}%</div><div className='flex gap-2'><button className='underline' onClick={()=>confirmMatch(m.saleId)}>confirmar pagamento</button></div></div>):<p className='text-sm text-muted-foreground'>Sem sugestões automáticas.</p>}</div>
  <div className="bg-white border rounded p-4"><h3 className="font-medium mb-2">Activity timeline</h3>{timeline.map((t:any)=><div key={t.id} className="text-xs border-b py-1">{new Date(t.createdAt).toLocaleString('pt-BR')} • {t.action}</div>)}</div></div>;
}
