ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "description" TEXT, ADD COLUMN IF NOT EXISTS "internalNotes" TEXT, ADD COLUMN IF NOT EXISTS "minStock" INTEGER NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS "category" TEXT, ADD COLUMN IF NOT EXISTS "unit" TEXT, ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "documentType" TEXT, ADD COLUMN IF NOT EXISTS "cep" TEXT, ADD COLUMN IF NOT EXISTS "street" TEXT, ADD COLUMN IF NOT EXISTS "streetNumber" TEXT, ADD COLUMN IF NOT EXISTS "complement" TEXT, ADD COLUMN IF NOT EXISTS "district" TEXT, ADD COLUMN IF NOT EXISTS "city" TEXT, ADD COLUMN IF NOT EXISTS "state" TEXT, ADD COLUMN IF NOT EXISTS "tags" TEXT[] DEFAULT ARRAY[]::TEXT[], ADD COLUMN IF NOT EXISTS "active" BOOLEAN NOT NULL DEFAULT TRUE, ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Seller" ADD COLUMN IF NOT EXISTS "commissionRate" DOUBLE PRECISION, ADD COLUMN IF NOT EXISTS "notes" TEXT, ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'CONFIRMED', ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT, ADD COLUMN IF NOT EXISTS "freight" DOUBLE PRECISION NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "category" TEXT, ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'CONFIRMED', ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Upload" ADD COLUMN IF NOT EXISTS "reviewStatus" TEXT NOT NULL DEFAULT 'PENDING', ADD COLUMN IF NOT EXISTS "customerId" TEXT, ADD COLUMN IF NOT EXISTS "saleId" TEXT, ADD COLUMN IF NOT EXISTS "transactionId" TEXT;
DO $$ BEGIN
ALTER TABLE "Upload" ADD CONSTRAINT "Upload_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
ALTER TABLE "Upload" ADD CONSTRAINT "Upload_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
ALTER TABLE "Upload" ADD CONSTRAINT "Upload_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
