'use client';
import { FormEvent, useMemo, useState } from 'react';import { useRouter, useSearchParams } from 'next/navigation';import { useErpData } from '@/components/erp/useErpData';import { PageHeader, SubmitButton } from '@/components/erp/shared';import { Input } from '@/components/ui/input';import { formatCurrency, formatDate } from '@/lib/utils';import { DataTable } from '@/components/erp/DataTable';import toast from 'react-hot-toast';
export default function Transactions(){const {data,refresh}=useErpData();const params=useSearchParams();const router=useRouter();const [f,setF]=useState({kind:'INCOME',description:'',amount:'0',category:'',status:'CONFIRMED',notes:'',paidAt:''});const [loading,setLoading]=useState(false);const type=params.get('type')||'';const q=params.get('q')||'';const setParam=(k:string,v:string)=>{const n=new URLSearchParams(params.toString());v?n.set(k,v):n.delete(k);router.replace(`/dashboard/transactions?${n}`)};
const rows=useMemo(()=> (data?.transactions||[]).filter((t:any)=>(!type||t.kind===type)&&(!q||t.description.toLowerCase().includes(q.toLowerCase())||String(t.category||'').toLowerCase().includes(q.toLowerCase()))),[data,type,q]);
const save=async(e:FormEvent)=>{e.preventDefault();setLoading(true);const r=await fetch('/api/v1/erp/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,amount:Number(f.amount),paidAt:f.paidAt?new Date(f.paidAt).toISOString():undefined})});setLoading(false);if(!r.ok)return toast.error('Falha');toast.success('Transação salva');setF({kind:'INCOME',description:'',amount:'0',category:'',status:'CONFIRMED',notes:'',paidAt:''});refresh();};
return <div className='space-y-4'><PageHeader title='Transações financeiras' subtitle='Entradas e saídas manuais, por vendas e OCR.'/><form onSubmit={save} className='bg-white border rounded p-4 grid md:grid-cols-4 gap-2 items-end'><select className='border rounded h-10 px-2' value={f.kind} onChange={e=>setF({...f,kind:e.target.value})}><option value='INCOME'>Entrada</option><option value='EXPENSE'>Saída</option></select><Input required placeholder='Descrição' value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><Input type='number' step='0.01' value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><Input placeholder='Categoria' value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><Input type='date' value={f.paidAt} onChange={e=>setF({...f,paidAt:e.target.value})}/><Input placeholder='Observação' value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><select className='border rounded h-10 px-2' value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>CONFIRMED</option><option>PENDING</option><option>CANCELLED</option></select><SubmitButton loading={loading}>Salvar transação</SubmitButton></form>
<div className='flex gap-2'><input className='border rounded h-9 px-3' placeholder='Buscar descrição/categoria' value={q} onChange={e=>setParam('q',e.target.value)}/><select className='border rounded h-9 px-2' value={type} onChange={e=>setParam('type',e.target.value)}><option value=''>Todos tipos</option><option value='INCOME'>Entrada</option><option value='EXPENSE'>Saída</option></select></div>
<DataTable rows={rows} columns={[{key:'kind',label:'Tipo'},{key:'source',label:'Origem'},{key:'category',label:'Categoria'},{key:'description',label:'Descrição'},{key:'amount',label:'Valor',render:(t:any)=>formatCurrency(t.amount)},{key:'status',label:'Status'},{key:'paidAt',label:'Data',render:(t:any)=>formatDate(t.paidAt)}]} />
</div>}
